### PR TITLE
Async content duplication

### LINKED ISSUE #17: Fire-and-forget content appending model is unsuitable
Consider `HttpMessageExtensions.CreateHarResponse(HttpResponseMessage)`:

```cs
var output = new Response { … };
if (response.Content != null)
{
  _ = output.AppendContentAsync(…);
}
```

If `AppendContentAsync` throws, the exception cannot be observed during testing; moreover, while automated tests can await the mock response, they can't await copying the content bytes, should that process be genuinely async.

### PR DESCRIPTION
**Pull request by jblam**
Resolves #17

### CODE REVIEW

File: HarClient/HarContent.cs [hunk 1]
```diff
@@ -14,14 +14,46 @@ namespace JBlam.HarClient
 {
     class HarContent : HttpContent
     {
-        public HarContent(HttpContent innerContent)
+        public static HarContent WrapContent(HttpRequestMessage requestMessage)
```
Comment (jblam) [inline HarClient/HarContent.cs:17]: Nullcheck public API member

File: HarClient/HarEntrySource.cs [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+            return AppendContentAsync(harContent, response);
+            
+            static async Task<Response> AppendContentAsync(HarContent content, Response partialResponse)
+            {
+                partialResponse.Content = await content.GetContent();
+                return partialResponse;
+            }
+        }
+
+        public async Task<Entry> CreateEntryAsync(CancellationToken cancellationToken)
```
Comment (jblam) [inline HarClient/HarEntrySource.cs:81]: Create test which illustrates this works, or remove cancellationtoken from the API

File: HarDemoHost/HarDemoHost.csproj [hunk 3]
```diff
@@ -12,4 +12,6 @@
     </PackageReference>
   </ItemGroup>
 
+  <ProjectExtensions><VisualStudio><UserProperties wwwroot_4firefox_1har__JsonSchema="https://json.schemastore.org/webjobs-list" /></VisualStudio></ProjectExtensions>
```
Comment (jblam) [inline HarDemoHost/HarDemoHost.csproj]: Remove

File: HarClient/HarEntrySource.cs [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+                : await this.response;
+            return new Entry
+            {
+                Cache = new Cache(),
+                Request = request,
+                Response = response,
+                StartedDateTime = startTime,
+                Timings = new Timings
+                {
+                    Send = sendTime?.TotalMilliseconds ?? -1,
```
Comment (jblam) [inline HarClient/HarEntrySource.cs:119]: Insert TODO or document correctness of Timings instantiation

File: HarClient/HarEntrySource.cs [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+                },
+                Time = sendTime?.TotalMilliseconds ?? -1,
```
Comment (jblam) [inline HarClient/HarEntrySource.cs:121]: Insert TODO or document correctness of Time.

Consider implementing this as a pure function of a Timings

File: HarClient/HarEntrySource.cs [hunk 6]
```diff
@@ -0,0 +1,102 @@
...
+        {
+            var request = cancellationToken.IsCancellationRequested
+                ? null
+                : await this.request;
+            var response = this.response == null || cancellationToken.IsCancellationRequested
+                ? null
+                : await this.response;
+            return new Entry
+            {
+                Cache = new Cache(),
```
Comment (jblam) [inline HarClient/HarEntrySource.cs:111]: Insert TODO or research caching behaviour for HttpClient

File: HarClient/HarEntrySource.cs [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+
+        internal static Header AsHeader(KeyValuePair<string, IEnumerable<string>> h) => new Header
+        {
+            Name = h.Key,
+            Value = string.Join(",", h.Value)
+        };
+        Task<Request> GetRequestAsync(HttpRequestMessage httpRequest)
+        {
+            var harContent = HarContent.WrapContent(httpRequest);
+            var request = new Request
```
Comment (jblam) [inline HarClient/HarEntrySource.cs:43]: Insert test which fails because QueryString is not implemented

Comment (jblam) [inline HarClient/HarEntrySource.cs:43]: Address lack of impl for Cookies somehow.

File: HarClient.Tests/HarSerialisationBehaviour.cs [hunk 8]
```diff
@@ -67,26 +71,28 @@ public void UrlEncodedContentRequestIsValid()
...
-            var harResponse = stringResponse.CreateHarResponse();
-            Assert.IsNotNull(harResponse.Content?.Text);
-            HarAssert.IsValidResponse(harResponse);
+            var sut = new HarEntrySource(arbitraryRequest, default);
+            sut.SetResponse(stringResponse);
+            var entry = await sut.CreateEntryAsync(default);
+            Assert.IsNotNull(entry.Response);
+            Assert.IsNotNull(entry.Response.Content?.Text);
+            HarAssert.IsValidResponse(entry.Response);
         }
```
Comment (jblam) [inline HarClient.Tests/HarSerialisationBehaviour.cs:97]: Ensure that HarAssert validates empty response content

Comment (jblam) [reply HarClient.Tests/HarSerialisationBehaviour.cs:97]: Also coverage for non-text content in request and response

File: HarClient/HarContent.cs (hunk 1 above)
Comment (jblam) [reply HarClient/HarContent.cs:17]: WONTFIX: class is not public.

(ED: with nullable reference types switched on, it does complain.)

File: HarClient/HarEntrySource.cs (hunk 2 above)
Comment (jblam) [reply HarClient/HarEntrySource.cs:81]: Changed the implementation so it's effective.

File: HarClient/HarEntrySource.cs (hunk 4 above)
Comment (jblam) [reply HarClient/HarEntrySource.cs:119]: Added reference to #11

File: HarClient/HarEntrySource.cs (hunk 6 above)
Comment (jblam) [reply HarClient/HarEntrySource.cs:111]: Created #20; referred in comment.

File: HarClient/HarEntrySource.cs (hunk 7 above)
Comment (jblam) [reply HarClient/HarEntrySource.cs:43]: Added #21; noted in comment

File: HarClient.Tests/HarSerialisationBehaviour.cs (hunk 8 above)
Comment (jblam) [reply HarClient.Tests/HarSerialisationBehaviour.cs:97]: WONTFIX; see #19

File: HarClient/HarEntrySource.cs (hunk 5 above)
Comment (jblam) [reply HarClient/HarEntrySource.cs:121]: There's a TODO referring to #11 right above it, so that should be fine.
