### PR TITLE
Redirects

### LINKED ISSUE #3: Redirects are invisible by default
The default behaviour of the default `HttpClientHandler` and `SocketsHttpHandler` automatically handle 3xx redirects, so the delegating handler will never observe them.

We should make a best effort attempt to reproduce the observable behaviour of the inner handler, but we should attempt to observe the redirects and log them in the HAR.

For example, 

```cs
#if NETCOREAPP2_1
            if (innerHandler is SocketsHttpHandler socketsHttpHandler)
                socketsHttpHandler.AllowAutoRedirect = false;
#endif
            if (innerHandler is HttpClientHandler httpClientHandler)
                httpClientHandler.AllowAutoRedirect = false;
```

### PR DESCRIPTION
**Pull request by jblam**
Fixes #3

### CODE REVIEW

File: HarClient/HarMessageHandler.cs [hunk 1]
```diff
@@ -54,13 +84,53 @@ public HarMessageHandler(HttpMessageHandler innerHandler) : base(innerHandler)
...
+            var nextRequest = request ?? throw new ArgumentNullException(nameof(request));
+            var redirectSet = new HashSet<Uri>
+            {
+                nextRequest.RequestUri
+            };
+            while (true)
+            {
+                var response = await RequestOne(nextRequest, cancellationToken).ConfigureAwait(false);
+                if (response != null &&
+                    response.IsRedirect(out var location) &&
```
Comment (jblam) [inline HarClient/HarMessageHandler.cs:108]: Most likely we should not e.g. redirect a POST; at least not with another POST.

Research required.

File: HarClient/HttpExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+using System.Text;
+
+namespace JBlam.HarClient
+{
+    static class HttpExtensions
+    {
+        public static HttpRequestMessage WithHeaders(this HttpRequestMessage message, HttpHeaders originalHeaders)
+        {
+            // Cursory examination of HttpHeaders source code indicates that this should never throw
+            message.Headers.AddRange(originalHeaders);
```
Comment (jblam) [inline HarClient/HttpExtensions.cs:15]: Not covered by tests

File: HarClient/HttpExtensions.cs [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+            return message;
+        }
+        public static HttpRequestMessage CreateRedirectRequest(this HttpResponseMessage response, HttpRequestMessage originalRequest) =>
+            new HttpRequestMessage(originalRequest.Method, new Uri(originalRequest.RequestUri, response.Headers.Location))
```
Comment (jblam) [inline HarClient/HttpExtensions.cs]: `originalRequest.Method` → a bit suspect.

File: HarClient/RedirectPolicy.cs [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+        /// Gets the observable auto redirect policy. If true, the handler will follow redirects;
+        /// otherwise, it will return any redirect response messages directly.
+        /// </summary>
+        public bool FollowRedirects { get; }
+        /// <summary>
+        /// Gets the inner-handler auto redirect policy. If true, the inner handler's auto redirect
+        /// behaviour will be suppressed (where possible). Otherwise, the inner handler will behave
+        /// as it was originally configured.
+        /// </summary>
+        public bool SuppressInnerAutoRedirect { get; }
```
Comment (jblam) [inline HarClient/RedirectPolicy.cs:46]: Consider if we want this to be "requested inner behaviour" `bool?`

File: HarClient/HarMessageHandler.cs (hunk 1 above)
Comment (jblam) [reply HarClient/HarMessageHandler.cs:108]: Tested native behaviour, and reimplemented that.

File: HarClient/HttpExtensions.cs (hunk 3 above)
Comment (jblam) [reply HarClient/HttpExtensions.cs]: Unsuspected,

File: HarClient/HttpExtensions.cs (hunk 2 above)
Comment (jblam) [reply HarClient/HttpExtensions.cs:15]: Now covered.

File: HarClient/RedirectPolicy.cs (hunk 4 above)
Comment (jblam) [reply HarClient/RedirectPolicy.cs:46]: Bearing in mind that "auto redirect" is a _feature_, it makes a certain amount of sense that we'd be _suppressing_ (disabling) _the feature_ here.

#WONTFIX
